# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Jan 06 18:10:41 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 448)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 151, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.fillercomboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.fillercomboBox.setObjectName("fillercomboBox")
        self.verticalLayout_2.addWidget(self.fillercomboBox)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.gasBuyercomboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.gasBuyercomboBox.setObjectName("gasBuyercomboBox")
        self.verticalLayout_2.addWidget(self.gasBuyercomboBox)
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.tankNrcomboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.tankNrcomboBox.setObjectName("tankNrcomboBox")
        self.verticalLayout_2.addWidget(self.tankNrcomboBox)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.centralWidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(190, 20, 81, 99))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.bottleSizecomboBox = QtGui.QComboBox(self.verticalLayoutWidget_3)
        self.bottleSizecomboBox.setObjectName("bottleSizecomboBox")
        self.bottleSizecomboBox.addItem("")
        self.bottleSizecomboBox.addItem("")
        self.bottleSizecomboBox.addItem("")
        self.bottleSizecomboBox.addItem("")
        self.bottleSizecomboBox.addItem("")
        self.bottleSizecomboBox.addItem("")
        self.bottleSizecomboBox.addItem("")
        self.bottleSizecomboBox.addItem("")
        self.bottleSizecomboBox.addItem("")
        self.bottleSizecomboBox.addItem("")
        self.verticalLayout_4.addWidget(self.bottleSizecomboBox)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.maxTryckcomboBox = QtGui.QComboBox(self.verticalLayoutWidget_3)
        self.maxTryckcomboBox.setObjectName("maxTryckcomboBox")
        self.verticalLayout_4.addWidget(self.maxTryckcomboBox)
        self.line = QtGui.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(-10, 180, 721, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.flaskTrycklineEdit = QtGui.QLineEdit(self.centralWidget)
        self.flaskTrycklineEdit.setGeometry(QtCore.QRect(530, 40, 91, 22))
        self.flaskTrycklineEdit.setObjectName("flaskTrycklineEdit")
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(530, 20, 101, 16))
        self.label_5.setObjectName("label_5")
        self.formLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(530, 70, 72, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.partialO2lineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.partialO2lineEdit.setObjectName("partialO2lineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.partialO2lineEdit)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.PartialHelineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.PartialHelineEdit.setObjectName("PartialHelineEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.PartialHelineEdit)
        self.prCalcpushButton = QtGui.QPushButton(self.centralWidget)
        self.prCalcpushButton.setGeometry(QtCore.QRect(570, 140, 141, 28))
        self.prCalcpushButton.setObjectName("prCalcpushButton")
        self.finalPressurelineEdit = QtGui.QLineEdit(self.centralWidget)
        self.finalPressurelineEdit.setGeometry(QtCore.QRect(640, 40, 71, 22))
        self.finalPressurelineEdit.setObjectName("finalPressurelineEdit")
        self.label_9 = QtGui.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(640, 20, 53, 16))
        self.label_9.setObjectName("label_9")
        self.formLayoutWidget_2 = QtGui.QWidget(self.centralWidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(640, 70, 72, 61))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.finalPHelineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.finalPHelineEdit.setObjectName("finalPHelineEdit")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.finalPHelineEdit)
        self.finalPO2lineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.finalPO2lineEdit.setObjectName("finalPO2lineEdit")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.finalPO2lineEdit)
        self.label_11 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(250, 200, 181, 181))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayoutWidget_3 = QtGui.QWidget(self.frame)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(20, 30, 125, 101))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_15 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_15)
        self.O2AnalyseratlineEdit = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.O2AnalyseratlineEdit.setObjectName("O2AnalyseratlineEdit")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.O2AnalyseratlineEdit)
        self.label_16 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_16)
        self.HeAnalyseratlineEdit = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.HeAnalyseratlineEdit.setObjectName("HeAnalyseratlineEdit")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.HeAnalyseratlineEdit)
        self.label_17 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_17)
        self.luftAnalyseratlineEdit = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.luftAnalyseratlineEdit.setObjectName("luftAnalyseratlineEdit")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.luftAnalyseratlineEdit)
        self.label_18 = QtGui.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.AnalyzeReadypushButton = QtGui.QPushButton(self.frame)
        self.AnalyzeReadypushButton.setGeometry(QtCore.QRect(10, 140, 161, 28))
        self.AnalyzeReadypushButton.setObjectName("AnalyzeReadypushButton")
        self.frame_2 = QtGui.QFrame(self.centralWidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 200, 201, 181))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayoutWidget = QtGui.QWidget(self.frame_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 171, 100))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 0, 1, 1)
        self.o2FyllTryckLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.o2FyllTryckLabel.setObjectName("o2FyllTryckLabel")
        self.gridLayout_2.addWidget(self.o2FyllTryckLabel, 1, 1, 1, 1)
        self.HeFyllTryckHelabel = QtGui.QLabel(self.gridLayoutWidget)
        self.HeFyllTryckHelabel.setObjectName("HeFyllTryckHelabel")
        self.gridLayout_2.addWidget(self.HeFyllTryckHelabel, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 3, 0, 1, 1)
        self.LuftFyllTrycklabel = QtGui.QLabel(self.gridLayoutWidget)
        self.LuftFyllTrycklabel.setObjectName("LuftFyllTrycklabel")
        self.gridLayout_2.addWidget(self.LuftFyllTrycklabel, 3, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.startFillpushButton = QtGui.QPushButton(self.frame_2)
        self.startFillpushButton.setGeometry(QtCore.QRect(60, 140, 93, 28))
        self.startFillpushButton.setObjectName("startFillpushButton")
        self.frame_3 = QtGui.QFrame(self.centralWidget)
        self.frame_3.setGeometry(QtCore.QRect(450, 200, 181, 171))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_20 = QtGui.QLabel(self.frame_3)
        self.label_20.setGeometry(QtCore.QRect(40, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.PaymentpushButton = QtGui.QPushButton(self.frame_3)
        self.PaymentpushButton.setGeometry(QtCore.QRect(40, 130, 93, 28))
        self.PaymentpushButton.setObjectName("PaymentpushButton")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.frame_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 169, 87))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_23 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 4, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 2, 0, 1, 1)
        self.Prislabel = QtGui.QLabel(self.gridLayoutWidget_2)
        self.Prislabel.setObjectName("Prislabel")
        self.gridLayout.addWidget(self.Prislabel, 4, 1, 1, 1)
        self.boughtHelabel = QtGui.QLabel(self.gridLayoutWidget_2)
        self.boughtHelabel.setObjectName("boughtHelabel")
        self.gridLayout.addWidget(self.boughtHelabel, 3, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 3, 0, 1, 1)
        self.boughtO2label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.boughtO2label.setObjectName("boughtO2label")
        self.gridLayout.addWidget(self.boughtO2label, 2, 1, 1, 1)
        self.boughtHeMolLlabel = QtGui.QLabel(self.gridLayoutWidget_2)
        self.boughtHeMolLlabel.setObjectName("boughtHeMolLlabel")
        self.gridLayout.addWidget(self.boughtHeMolLlabel, 3, 2, 1, 1)
        self.boughtO2MolLabel = QtGui.QLabel(self.gridLayoutWidget_2)
        self.boughtO2MolLabel.setObjectName("boughtO2MolLabel")
        self.gridLayout.addWidget(self.boughtO2MolLabel, 2, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 1, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 1, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.centralWidget)
        self.label_24.setGeometry(QtCore.QRect(170, 150, 71, 16))
        self.label_24.setObjectName("label_24")
        self.FyllNrlabel = QtGui.QLabel(self.centralWidget)
        self.FyllNrlabel.setGeometry(QtCore.QRect(240, 150, 53, 16))
        self.FyllNrlabel.setObjectName("FyllNrlabel")
        self.label_27 = QtGui.QLabel(self.centralWidget)
        self.label_27.setGeometry(QtCore.QRect(350, 10, 81, 16))
        self.label_27.setObjectName("label_27")
        self.gridLayoutWidget_3 = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(290, 40, 210, 80))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_28 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 2, 0, 1, 1)
        self.bankHeTryckBeforelineEdit = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.bankHeTryckBeforelineEdit.setObjectName("bankHeTryckBeforelineEdit")
        self.gridLayout_3.addWidget(self.bankHeTryckBeforelineEdit, 1, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 0, 1, 1, 1)
        self.HeBankTryckAfterlineEdit = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.HeBankTryckAfterlineEdit.setObjectName("HeBankTryckAfterlineEdit")
        self.gridLayout_3.addWidget(self.HeBankTryckAfterlineEdit, 1, 2, 1, 1)
        self.O2BankTryckBeforelineEdit = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.O2BankTryckBeforelineEdit.setObjectName("O2BankTryckBeforelineEdit")
        self.gridLayout_3.addWidget(self.O2BankTryckBeforelineEdit, 2, 1, 1, 1)
        self.O2BankTryckAfterlineEdit = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.O2BankTryckAfterlineEdit.setObjectName("O2BankTryckAfterlineEdit")
        self.gridLayout_3.addWidget(self.O2BankTryckAfterlineEdit, 2, 2, 1, 1)
        self.label_31 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 0, 2, 1, 1)
        self.HeBankVolymlineEdit = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.HeBankVolymlineEdit.setObjectName("HeBankVolymlineEdit")
        self.gridLayout_3.addWidget(self.HeBankVolymlineEdit, 1, 3, 1, 1)
        self.O2BankVolymlineEdit = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.O2BankVolymlineEdit.setObjectName("O2BankVolymlineEdit")
        self.gridLayout_3.addWidget(self.O2BankVolymlineEdit, 2, 3, 1, 1)
        self.label_32 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 0, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 720, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Fyllare", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Gas köpare", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Flask Nr.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Flaskstorlek", None, QtGui.QApplication.UnicodeUTF8))
        self.bottleSizecomboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.bottleSizecomboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.bottleSizecomboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.bottleSizecomboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.bottleSizecomboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.bottleSizecomboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.bottleSizecomboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.bottleSizecomboBox.setItemText(7, QtGui.QApplication.translate("MainWindow", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.bottleSizecomboBox.setItemText(8, QtGui.QApplication.translate("MainWindow", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.bottleSizecomboBox.setItemText(9, QtGui.QApplication.translate("MainWindow", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "max tryck", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Nuvarande tryck", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "O2 %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "He %", None, QtGui.QApplication.UnicodeUTF8))
        self.prCalcpushButton.setText(QtGui.QApplication.translate("MainWindow", "Kalkylera fyll trycken", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Slut tryck", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "O2 %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "He %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "O2 %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "He %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Flask Tryck", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Analyserade resultat", None, QtGui.QApplication.UnicodeUTF8))
        self.AnalyzeReadypushButton.setText(QtGui.QApplication.translate("MainWindow", "Analysen klar, gå till kassa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Fyll He till:", None, QtGui.QApplication.UnicodeUTF8))
        self.o2FyllTryckLabel.setText(QtGui.QApplication.translate("MainWindow", "000", None, QtGui.QApplication.UnicodeUTF8))
        self.HeFyllTryckHelabel.setText(QtGui.QApplication.translate("MainWindow", "000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Fyll O2 till:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Fyll luft till:", None, QtGui.QApplication.UnicodeUTF8))
        self.LuftFyllTrycklabel.setText(QtGui.QApplication.translate("MainWindow", "000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Fyll gas till dessa tryck", None, QtGui.QApplication.UnicodeUTF8))
        self.startFillpushButton.setText(QtGui.QApplication.translate("MainWindow", "Fyll gas", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Mängd gas", None, QtGui.QApplication.UnicodeUTF8))
        self.PaymentpushButton.setText(QtGui.QApplication.translate("MainWindow", "Betala", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Pris:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "O2", None, QtGui.QApplication.UnicodeUTF8))
        self.Prislabel.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.boughtHelabel.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "He", None, QtGui.QApplication.UnicodeUTF8))
        self.boughtO2label.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.boughtHeMolLlabel.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.boughtO2MolLabel.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Liter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Kmol", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Fyllning nr:", None, QtGui.QApplication.UnicodeUTF8))
        self.FyllNrlabel.setText(QtGui.QApplication.translate("MainWindow", "XXX", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Bank Flaskor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "He", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "O2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Tryck före", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Tryck efter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Volym", None, QtGui.QApplication.UnicodeUTF8))

